// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelLogMicroService.Data;

#nullable disable

namespace TravelLogMicroService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260305083940_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TravelLogMicroService.Models.TravelLogs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("DistanceKm")
                        .HasColumnType("double");

                    b.Property<double>("EstimatedCO2")
                        .HasColumnType("double");

                    b.Property<int>("ObservationId")
                        .HasColumnType("int");

                    b.Property<int>("TravelMode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TravelLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
